name: On Commit

"on":
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]

permissions:
  contents: read

jobs:
  flow:
    uses: cloudvoyant/premise/.github/workflows/release-platform.yml@v0
    with:
      flow: on-commit
      release: none
