package core

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"
)

const NativeTemplateSource = "cloudvoyant/premise"

type Selection struct {
	Source string
	Name   string
	Local  bool
}

func ParseSelector(selector string) (Selection, error) {
	separator := strings.LastIndex(selector, ":")
	if separator < 0 || separator == len(selector)-1 {
		return Selection{}, fmt.Errorf("template selector %q must end with :<template>", selector)
	}
	source := selector[:separator]
	name := selector[separator+1:]
	if err := ValidateTemplateName(name); err != nil {
		return Selection{}, err
	}
	if source == "" {
		source = NativeTemplateSource
	}
	local := source == "." || filepath.IsAbs(source) || strings.HasPrefix(source, "./") || strings.HasPrefix(source, "../")
	return Selection{Source: source, Name: name, Local: local}, nil
}

func ResolveTemplateSource(ctx context.Context, workspaceRoot, selector string) (string, Selection, error) {
	selection, err := ParseSelector(selector)
	if err != nil {
		return "", Selection{}, err
	}
	if selection.Local {
		if filepath.IsAbs(selection.Source) {
			return filepath.Clean(selection.Source), selection, nil
		}
		path, err := filepath.Abs(filepath.Join(workspaceRoot, selection.Source))
		if err != nil {
			return "", Selection{}, fmt.Errorf("resolve local template source: %w", err)
		}
		return path, selection, nil
	}

	root, err := resolveRepository(ctx, selection.Source)
	if err != nil {
		return "", Selection{}, err
	}
	return root, selection, nil
}

func TemplateDirectory(sourceRoot, name string) (string, error) {
	if err := ValidateTemplateName(name); err != nil {
		return "", err
	}
	root, err := filepath.Abs(sourceRoot)
	if err != nil {
		return "", fmt.Errorf("resolve template root: %w", err)
	}
	path := filepath.Join(root, "templates", name)
	relative, err := filepath.Rel(root, path)
	if err != nil || escapesRoot(relative) {
		return "", fmt.Errorf("template path escapes source root")
	}
	info, err := os.Stat(path)
	if err != nil {
		return "", fmt.Errorf("inspect template directory: %w", err)
	}
	if !info.IsDir() {
		return "", fmt.Errorf("template path %s is not a directory", path)
	}
	return path, nil
}

type ScaffoldRequest struct {
	Source       string
	Destination  string
	Replacements map[string]string
}

func Scaffold(request ScaffoldRequest) error {
	source, err := filepath.Abs(request.Source)
	if err != nil {
		return fmt.Errorf("resolve scaffold source: %w", err)
	}
	destination, err := filepath.Abs(request.Destination)
	if err != nil {
		return fmt.Errorf("resolve scaffold destination: %w", err)
	}
	if source == destination {
		return errors.New("scaffold source and destination must differ")
	}
	if info, err := os.Stat(source); err != nil {
		return fmt.Errorf("inspect scaffold source: %w", err)
	} else if !info.IsDir() {
		return fmt.Errorf("scaffold source %s is not a directory", source)
	}
	if _, err := os.Lstat(destination); err == nil {
		return fmt.Errorf("destination %s already exists", destination)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect scaffold destination: %w", err)
	}

	parent := filepath.Dir(destination)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return fmt.Errorf("create destination parent: %w", err)
	}
	stage, err := os.MkdirTemp(parent, "."+filepath.Base(destination)+".premise-*")
	if err != nil {
		return fmt.Errorf("create scaffold staging directory: %w", err)
	}
	committed := false
	defer func() {
		if !committed {
			_ = os.RemoveAll(stage)
		}
	}()

	replacer := literalReplacer(request.Replacements)
	if err := copyTree(source, stage, replacer); err != nil {
		return err
	}
	if err := os.Rename(stage, destination); err != nil {
		return fmt.Errorf("commit scaffold: %w", err)
	}
	committed = true
	return nil
}

func RenderTemplateMise(kind string) (string, error) {
	tasks, err := ContractTasks(kind)
	if err != nil {
		return "", err
	}
	name := "premise-" + kind
	var content strings.Builder
	content.WriteString("# Generated by premise. Replace echo commands with real implementations.\n\n")
	for _, task := range tasks {
		fmt.Fprintf(&content, "[tasks.%q]\n", task)
		fmt.Fprintf(&content, "description = %q\n", "Run the "+task+" contract")
		fmt.Fprintf(&content, "run = %q\n\n", "echo \""+name+": "+task+"\"")
	}
	return content.String(), nil
}

func InitializeTemplate(root, kind string) (string, error) {
	manifestPath := filepath.Join(root, ManifestFilename)
	manifest, err := LoadManifest(manifestPath)
	if err != nil {
		return "", err
	}
	if _, err := manifest.FindTemplate(kind); err == nil {
		return "", fmt.Errorf("template %q is already declared", kind)
	}
	if _, err := KindDirectory(kind); err != nil {
		return "", err
	}

	templatePath := filepath.Join(root, "templates", kind)
	if _, err := os.Lstat(templatePath); err == nil {
		return "", fmt.Errorf("template directory %s already exists", templatePath)
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", fmt.Errorf("inspect template directory: %w", err)
	}
	if err := os.MkdirAll(templatePath, 0o755); err != nil {
		return "", fmt.Errorf("create template directory: %w", err)
	}
	created := true
	defer func() {
		if created {
			_ = os.RemoveAll(templatePath)
		}
	}()

	mise, err := RenderTemplateMise(kind)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(templatePath, "mise.toml"), []byte(mise), 0o644); err != nil {
		return "", fmt.Errorf("write template mise.toml: %w", err)
	}
	manifest.Templates = append(manifest.Templates, Template{
		Name:    kind,
		Kind:    kind,
		Version: "0.1.0",
		Questions: []Question{{
			Prompt:   kindLabel(kind) + " name:",
			Type:     "string",
			Populate: "name",
		}},
		Substitutions: map[string]string{"premise-" + kind: "name"},
	})
	if err := SaveManifest(manifestPath, manifest); err != nil {
		return "", err
	}
	created = false
	return templatePath, nil
}

func TestTemplateContracts(ctx context.Context, root string, manifest Config, stdout, stderr io.Writer) error {
	if len(manifest.Templates) == 0 {
		return errors.New("manifest declares no templates")
	}
	var failures []error
	for _, template := range manifest.Templates {
		directory, err := TemplateDirectory(root, template.Name)
		if err != nil {
			failures = append(failures, fmt.Errorf("template %s: %w", template.Name, err))
			continue
		}
		tasks, err := ContractTasks(template.Kind)
		if err != nil {
			failures = append(failures, fmt.Errorf("template %s: %w", template.Name, err))
			continue
		}
		for _, task := range tasks {
			fmt.Fprintf(stdout, "[%s] mise run %s\n", template.Name, task)
			command := exec.CommandContext(ctx, "mise", "run", task)
			command.Dir = directory
			command.Env = append(os.Environ(), "PREMISE_TEMPLATE_TEST=1")
			command.Stdout = stdout
			command.Stderr = stderr
			if err := command.Run(); err != nil {
				failures = append(failures, fmt.Errorf("template %s task %s failed: %w", template.Name, task, err))
			}
		}
	}
	return errors.Join(failures...)
}

func copyTree(source, destination string, replacer *strings.Replacer) error {
	return filepath.WalkDir(source, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		relative, err := filepath.Rel(source, path)
		if err != nil || escapesRoot(relative) {
			return fmt.Errorf("source entry escapes scaffold root: %s", path)
		}
		target := destination
		if relative != "." {
			target = filepath.Join(destination, relative)
		}
		if !inside(destination, target) {
			return fmt.Errorf("destination entry escapes scaffold root: %s", target)
		}

		info, err := entry.Info()
		if err != nil {
			return fmt.Errorf("inspect scaffold entry %s: %w", path, err)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			link, err := os.Readlink(path)
			if err != nil {
				return fmt.Errorf("read scaffold symlink %s: %w", path, err)
			}
			if filepath.IsAbs(link) || escapesRoot(filepath.Join(filepath.Dir(relative), link)) {
				return fmt.Errorf("scaffold symlink %s points outside the template", relative)
			}
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return fmt.Errorf("create symlink parent: %w", err)
			}
			if err := os.Symlink(link, target); err != nil {
				return fmt.Errorf("copy scaffold symlink %s: %w", relative, err)
			}
			return nil
		}
		if info.IsDir() {
			if err := os.MkdirAll(target, info.Mode().Perm()); err != nil {
				return fmt.Errorf("create scaffold directory %s: %w", relative, err)
			}
			if err := os.Chmod(target, info.Mode().Perm()); err != nil {
				return fmt.Errorf("preserve directory permissions %s: %w", relative, err)
			}
			return nil
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("unsupported scaffold entry %s", relative)
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read scaffold file %s: %w", relative, err)
		}
		if replacer != nil && isText(data) {
			data = []byte(replacer.Replace(string(data)))
		}
		if err := os.WriteFile(target, data, info.Mode().Perm()); err != nil {
			return fmt.Errorf("write scaffold file %s: %w", relative, err)
		}
		if err := os.Chmod(target, info.Mode().Perm()); err != nil {
			return fmt.Errorf("preserve file permissions %s: %w", relative, err)
		}
		return nil
	})
}

func literalReplacer(replacements map[string]string) *strings.Replacer {
	if len(replacements) == 0 {
		return nil
	}
	tokens := make([]string, 0, len(replacements))
	for token := range replacements {
		tokens = append(tokens, token)
	}
	sort.Slice(tokens, func(i, j int) bool {
		if len(tokens[i]) == len(tokens[j]) {
			return tokens[i] < tokens[j]
		}
		return len(tokens[i]) > len(tokens[j])
	})
	pairs := make([]string, 0, len(tokens)*2)
	for _, token := range tokens {
		pairs = append(pairs, token, replacements[token])
	}
	return strings.NewReplacer(pairs...)
}

func isText(data []byte) bool {
	return !bytes.ContainsRune(data, 0) && utf8.Valid(data)
}

func inside(root, path string) bool {
	relative, err := filepath.Rel(root, path)
	return err == nil && !escapesRoot(relative)
}

func kindLabel(kind string) string {
	if kind == "app" {
		return "App"
	}
	return "Library"
}
