name: On Merge

"on":
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: stable-release
  cancel-in-progress: false

jobs:
  flow:
    uses: ./.github/workflows/release-platform.yml
    with:
      flow: on-merge
      release: auto
      package-environment: production
